### ISSUE TITLE
[SUGGESTION] Add native compatibility with ShipLoot, BetterItemScan and HoldScanButton

### ISSUE THREAD

**Issue by Nyxlanders** [Saradora/ScanTweaks#1]
These are the most downloaded mods that change how the scan works, so would be nice to your mod work with them.

**Comment by Saradora** [comment]
Thank you for your feedback c:
I have reworked the code to allow compatibility with ShipLoot and HoldScanButton!
I'll upload the updated version at a later date when I'll have time to properly test it c:

I don't think i'll try adding compatibility for BetterItemScan though as we both heavily modify the code of the scan in very different ways :c
