### ISSUE TITLE
LethalConfig 1.4.1 Incompatibility

### ISSUE THREAD

**Issue by MissMavius** [Saradora/ScanTweaks#6]
Lethal Config version1.4.0 didn't have any conflicts with this mod, but the latest version makes this mod unable to scan anything at all.

**Comment by Saradora** [comment]
Do you have any logs, or a list of all the mods used? c:

I played yesterday and had LethalConfig 1.4.1 and could scan just fine, as well as my friends

**Comment by MissMavius** [comment]
It is not LethalConfig, after some testing I think I have narrowed it down to the mod NilsHUD.
The mods I have enabled to make this happen are the following:
ScanTweaks v1.5.1
LethalMDK v1.1.0
UnityMDK v1.2.0
NilsHUD v1.0.4
BepInExPack v5.4.2100
When download the previous version of NilsHUD v1.0.3, this doesn't happen.

**Comment by Saradora** [comment]
Mmm i can't seem to reproduce the error with those mods installed.

I'll try a bit more but otherwise I would probably need logs

**Comment by MissMavius** [comment]
Ah, I forgot to add LethalConfig v1.4.1 to the list of mods to make this happen.

**Comment by Saradora** [comment]
Ok yeah I managed to reproduce the issue, I couldn't do it with manually installed mods, but installing them via thunderstore does break things!

I'll see what I can do c:

**Comment by Saradora** [comment]
I found the issue, but it seems to be either an issue from NilsHUD or LethalConfig, they are literally breaking a Unity event that I'm listening to.

This is a pretty big issue, because it's a common Unity Event, and that means that any mod (or vanilla stuff) that listens to this also gets broken D:

**Comment by Saradora** [comment]
The issue should be resolved in the next coming NilsHUD update c:
