### ISSUE TITLE
Apparatus's price is overriding the total moon value on results screen

### ISSUE THREAD

**Issue by Terraformer9x** [Saradora/ScanTweaks#7]
For moon's that have an apparatus, the moon's total value is showing as the price of the apparatus.

**Comment by Saradora** [comment]
Thanks for the feedback!

I somehow never noticed that, my bad :o

I'll work on fixing that

**Comment by Saradora** [comment]
I think I fixed it, but i'll have to do some testing tomorrow before releasing a patch :D

Hopefully I'll have it released tomorrow c:

**Comment by Saradora** [comment]
Well, sorry for the delay, but I put out a patch today hopefully fixing this issue c:
I'll be closing this issue for now!
