### ISSUE TITLE
The shovel does not have a scanning node.

### ISSUE THREAD

**Issue by AJAL8000** [Saradora/ScanTweaks#8]
I don't know if there are other tools that also have the problem.

**Comment by Saradora** [comment]
Oh, yeah I think I see what went wrong, I'll fix it later today c:
Thank you for the report!!

Edit: I actually probably already fixed it, but I don't have time to do proper testing now, there should be a patch today though c:

**Comment by Saradora** [comment]
The bug should be fixed now! I will close this issue c:
